### ISSUE TITLE
unexpected error error="header field value cannot include CR/LF"

### ISSUE THREAD

**Issue by gokhandincer** [hfwang/fluent-plugin-google-cloud-storage#8]
Hello,
I am getting error like this;
```
2019-03-29 15:04:39 +0000 [error]: unexpected error error="header field value cannot include CR/LF"
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/2.5.0/net/http/header.rb:23:in `block in initialize_http_header'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/2.5.0/net/http/header.rb:16:in `each'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/2.5.0/net/http/header.rb:16:in `initialize_http_header'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/2.5.0/net/http/generic_request.rb:44:in `initialize'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:67:in `new'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:67:in `create_request'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:87:in `perform_request'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.8.6/lib/google/api_client/request.rb:163:in `send'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:648:in `block (2 levels) in execute!'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:645:in `block in execute!'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:636:in `execute!'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:368:in `discovery_document'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:413:in `discovered_api'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluent-plugin-google-cloud-storage-1.0.0/lib/fluent/plugin/out_google_cloud_storage.rb:102:in `prepare_client'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluent-plugin-google-cloud-storage-1.0.0/lib/fluent/plugin/out_google_cloud_storage.rb:78:in `configure'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/agent.rb:133:in `add_match'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/agent.rb:64:in `block in configure'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/agent.rb:57:in `each'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/agent.rb:57:in `configure'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/root_agent.rb:86:in `configure'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/engine.rb:129:in `configure'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/engine.rb:103:in `run_configure'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:489:in `run_configure'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:160:in `block in start'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:366:in `main_process'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:339:in `block in supervise'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:338:in `fork'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:338:in `supervise'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/supervisor.rb:156:in `start'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.5.0/gems/fluentd-0.12.43/bin/fluentd:8:in `<top (required)>'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2019-03-29 15:04:39 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<main>'
2019-03-29 15:04:39 +0000 [info]: process finished code=256
2019-03-29 15:04:39 +0000 [warn]: process died within 1 second. exit.
```

td-agent.conf

```
<source>
  @type forward
  # default port
  port 24221
  bind 127.0.0.1
</source>

<match test.debug>
  type google_cloud_storage
  service_email xxxxxx@xxxxx.iam.gserviceaccount.com
  service_pkcs12_path /opt/xxxxx.p12
  project_id xxxxx
  bucket_id xxxxx
  path test.debug/%Y/%m/%d/%H/${chunk_id}.log.gz
  output_include_time false
  output_include_tag  false
  buffer_path /var/log/td-agent/buffer/.test.debug
  # flush_interval 600s
  buffer_chunk_limit 128m
  time_slice_wait 300s
  compress gzip
</match>
```
But I don't understand why. Is there any clue. Thanks.

**Comment by pdehlke** [comment]
Fixed in #9
